### ISSUE TITLE
Striped article tables

### ISSUE THREAD

**Issue by TicClick** [cl8n/osu-wiki-status#2]
even a slightest tint of grey alternating with regular white rows would improve readability drastically (I personally misclick diff links sometimes)

```css
tr:nth-child(even) {
  background-color: #f8f8f8;
}
```
